### ISSUE TITLE
Can't Install in Linux

### ISSUE THREAD

**Issue by niranjanshr13** [OleStauning/NZBDrive#1]
Error:
./nzbmounter: error while loading shared libraries: libtinyxml.so.2.6.2: cannot open shared object file: No such file or directory

Can you make Docker Image of it.

**Comment by shillshocked** [comment]
Same here. And can't make:
`g++ -o nzbmounter NZBFuseDrive.o nzbmounter.o  -L ../NZBDriveLib -lNZBDrive -ltinyxml -lboost_thread -lboost_filesystem -lboost_system `pkg-config fuse --cflags --libs` `pkg-config --libs openssl`
/usr/bin/ld: cannot find -lNZBDrive
collect2: error: ld returned 1 exit status
make: *** [Makefile:9: nzbmounter] Error 1
`

**Comment by OleStauning** [comment]
libtinyxml.so.2.6.2 is a dynamically loaded library so it needs to be in a directory listed in the rpath. In case the .so-file is located in /usr/local/lib you can add this path (LD_LIBRARY_PATH=/usr/local/lib). I have included this path to the build/Makefile so nzbmounter will look in /usr/local/lib by default.
